# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yet Another Digital Native's Tech Blog
email: twofyw@tongji.edu.cn
description: >- # this means to ignore newlines until "baseurl:"
    Working on temporal data and embedding #ML.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://localhost" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: twofyw
github_username: twofyw

repository: Twofyw/twofyw.github.io

github_icon:
  repo:           https://github.com/twofyw

# Build settings
#markdown: kramdown
#theme: minima
#plugins:
  #- jekyll-feed

paginate:         5

# Build settings
markdown: kramdown
theme: jekyll-theme-hydeout
remote_theme: fongandrew/hydeout
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate  

# disqus
disqus:
  shortname: twofyw



#sidebar_home_link:  true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
